### ISSUE TITLE
Unable to customize. File '/config.txt' does not exist

### ISSUE THREAD

**Issue by iamashwin99** [flathub/org.raspberrypi.rpi-imager#17]
I am using the advanced menu  (Ctrl + Shift + X)  to set up WiFI credentials, but after writing  the sdcard, during the verification, I get the following error.
**Unable to customize. File '/config.txt' does not exist.**
![image](https://user-images.githubusercontent.com/46030335/148695434-bf454503-1922-4b2c-ac48-d1f1130e4a8c.png)
I am using Arch Linux and rpi-imager from flatpak.
This issue has also been reported here : https://github.com/raspberrypi/rpi-imager/issues/289

**Comment by eknme** [comment]
+1 on PopOs installed from PopOs Store. This issue does not exist with debian package.
