### ISSUE TITLE
Version 1.8.1-1 is out please update

### ISSUE THREAD

**Issue by DarkXero-dev** [flathub/org.raspberrypi.rpi-imager#30]
Version on flathub is seriously out of date please update... New version 1.8.1-1 is out.. 

Thanks

**Comment by ghisvail** [comment]
> Version on flathub is seriously out of date please update

The latest version was released 15 hours ago, and a new PR for it was submitted 10 hours ago.

I believe the only thing *serious* is your impatience at this point.
